### ISSUE TITLE
broken reflectionList cannot be regenerated

### ISSUE THREAD

**Issue by rivasdiaz** [gluonhq/client-gradle-plugin#27]
In my test project I included in the reflectionList an item that was not a valid class name, and after fixing it, the extra wrong class name keeps showing up in `build/client/gvm/reflectionconfig-mac.json`.

I've tried `./gradlew clean` and deleting `~/.gluon`, and the wrong entry keeps showing up.

Is that file cached somewhere outside the project? shouldn't it be clean on  `./gradlew clean`?

thanks

**Comment by jperedadnr** [comment]
There is no such caching. Try to kill any Java process that might still be running and try again? You can just edit the json file right after nativeCompile starts and see if it is correct.

**Comment by rivasdiaz** [comment]
It seems the problem goes away if I run the build process with `./gradlew --no-daemon nativeBuild`. 

So it's possible there is a problem related to running the plugin by a gradle daemon.

**Comment by rivasdiaz** [comment]
Another pointer that may help: when I have any class listed in the reflection list and run `./gradlew nativeBuild` multiple times, the list of classes is added multiple times to the end of the `build/client/gvm/reflectionconfig-mac.json` file. Which means the list is kept somewhere in a class that stays in memory in the daemon. I tried to look into the source code of the plugin. The issue seems to be inside `Omega.nativeCompile(...)` but that library seems to not be open source? (or not public yet?)

**Comment by jperedadnr** [comment]
I can reproduce the issue with gradle deamon enabled, and as you say, even clearing the previous build, the classes keep adding to the end of the json file after every run of `nativeCompile`.

This issue has to do with having a static reference to Omega. With the deamon enabled, the lists in Omega are not reset on every new build. An easy fix can be done in Omega just making sure all the required lists are properly reset.

In the meantime, running with `--no-daemon` or adding `org.gradle.daemon=false` to a `gradle.properties` file (project or user wise) solves the issue. 

Omega will be open sourced soon.

**Comment by jperedadnr** [comment]
It should be fixed by now. You can test with the plugin version `0.0.10-SNAPSHOT`, adding the `public-snapshots` repository to the project's setting.gradle file.

**Comment by jperedadnr** [comment]
The plugin 0.0.10 has been released.
