### ISSUE TITLE
Gradle doesn't work

### ISSUE THREAD

**Issue by lukasresch** [gluonhq/client-gradle-plugin#3]
After applying following to my gradle file:

>  plugins {
>     id 'application'
>     id 'org.openjfx.javafxplugin' version '0.0.5'
>     id 'com.gluonhq.client-gradle-plugin' version '0.0.1'
> }

I got the error-msg:

> Plugin [id: 'com.gluonhq.client-gradle-plugin', version: '0.0.1'] was not found in any of the following sources:
> 
> - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
> - Plugin Repositories (could not resolve plugin artifact 'com.gluonhq.client-gradle-plugin:com.gluonhq.client-gradle-plugin.gradle.plugin:0.0.1')
>   Searched in the following repositories:
>     Gradle Central Plugin Repository

I hope you can help me because I really want to try the plugin!

cu Lukas

**Comment by jperedadnr** [comment]
If you check the [docs](https://docs.gluonhq.com/client/#_1_apply_the_plugin_2), or the client [samples](https://github.com/gluonhq/client-samples/blob/master/Gradle/), you will notice the plugin is hosted at a custom repo, not the Gradle plugin portal yet. 

Include a settings.gradle file with it, like this [one](https://github.com/gluonhq/client-samples/blob/master/Gradle/HelloFX/settings.gradle).

However, I'll update the readme of this repository.

**Comment by shashaanktulsyan** [comment]
Not able to get this running
`gradlew.bat -c settings.gradle`
Output : 
`Plugin Repositories (could not resolve plugin artifact 'com.gluonhq.client-gradle-plugin:com.gluonhq.client-gradle-plugin.gradle.plugin:0.0.10') 
  Searched in the following repositories:
    maven(https://nexus.gluonhq.com/nexus/content/repositories/releases)
    Gradle Central Plugin Repository`

**Comment by jperedadnr** [comment]
@shashaanktulsyan This issue was already closed. Open a new one, and post your settings.gradle and build.gradle files.

**Comment by shashaanktulsyan** [comment]
> @shashaanktulsyan This issue was already closed. Open a new one, and post your settings.gradle and build.gradle files.

Is was actually a SSL certificate issue, the default Java_home which I had was using an older jvm which had some certificate issue and was not accepting the gluonhq nexus repository. 
Aplogies.
