### ISSUE TITLE
Generated APK is not installed

### ISSUE THREAD

**Issue by Ali-RS** [gluonhq/client-gradle-plugin#69]
Hi 

I am using this hello world Gradle example for testing it on Android. 

https://github.com/tlf30/graalVmTest
(It uses the latest plugin version)

I can successfully generate APK. I can find them inside this directory
`graalVmTest/build/client/aarch64-android/gvm/apk/bin/`

they are `graalVmTest.apk` and `graalVmTest.unaligned.apk`, but I can not install any of them on Android emulators. I tried to manually copy APKs to the emulator and install it from there but says app not installed. Tested on a bunch of emulators with android 5 and 7 and 9 but no success. (I could not test them on an Android device as I do not have an arm-v8 Android device)

I have tried them on Bliss OS and NoxPlayer emulators with no success.

Can someone confirm if this works for them? Anything there might be wrong I am doing? 

I Will appreciate any help.

btw, I am on Linux Mint 19.3 Tricia and I have installed `libstdc++-7` on it. And installed Graal VM from https://download2.gluonhq.com/substrate/graalvm/graalvm-svm-linux-20.1.0-ea+28.zip 

If you want you can get APKs from this link: 
https://drive.google.com/file/d/1soXvQe9l4o30OX1idBvJn8DGAevvkXnG/view?usp=sharing

Regards

**Comment by jperedadnr** [comment]
Try a device. The apk is built only for aarch64 architecture, not for x86_64, so it won't work.

**Comment by Ali-RS** [comment]
Ah, you are right, just confirmed those emulators were x86_64 and not aarch64.

Sorry for bothering and Thanks for your help.
