### ISSUE TITLE
Native Image Arguments

### ISSUE THREAD

**Issue by maroc81** [gluonhq/client-gradle-plugin#80]
Is there a way to pass arguments to native image? The maven plugin provides the configuration option "nativeImageArgs".  I don't see anything similar for the gradle plugin.

**Comment by gringofe** [comment]
Even though the maintainers do not seem to give a shit about this project (no issue has been answered), could anyone still help us out here? I also need to pass a few arguments.

**Comment by jperedadnr** [comment]
The Client gradle plugin uses `compilerArgs`:
https://github.com/gluonhq/client-gradle-plugin/blob/master/src/main/java/com/gluonhq/gradle/tasks/ConfigBuild.java#L130

while the Maven version uses `nativeImageArgs`:
https://github.com/gluonhq/client-maven-plugin/blob/master/src/main/java/com/gluonhq/NativeBaseMojo.java#L174
