### ISSUE TITLE
Could you tell me how to build native JavaFX application with Kotlin?

### ISSUE THREAD

**Issue by icuxika** [gluonhq/client-gradle-plugin#91]
`
fun main(args: Array<String>) {
    Application.launch(MainApp::class.java, *args)
}

class MainApp: Application() {
    override fun start(primaryStage: Stage?) {
        primaryStage?.let { stage ->
            stage.scene = Scene(Label("JavaFX"))
            stage.show()
        }
    }
}
`

>I got "Caused by: java.lang.NoSuchMethodException: xx.xx.MainApp.<init>()" when I executed the command "gradlew nativeRun".

**Comment by jperedadnr** [comment]
Add your class to the reflectionList. See https://docs.gluonhq.com/client/#_configuration. All the classes that are used reflectively should be included in such list. The plugin adds most of the JavaFX classes already.

**Comment by icuxika** [comment]
Thank you for your reply.  I'm using the gradle plugin, but I don't how to configure the reflectionlist in gradle.

**Comment by jperedadnr** [comment]
Like:

```
gluonClient {
       reflectionList = [
            "xx.xx.MainApp",
            "xx.xx.MainView",
           ...
    ]
}
```

**Comment by icuxika** [comment]
Thanks a lot!
